development:
  WHITELIST_IP_ADDRESSES: 192.168.0.1,192.168.0.9
  IP_ADDRESS_WHITELIST_ENABLED: true

test:
  WHITELIST_IP_ADDRESSES: 62.0.0.0,62.255.255.255
  IP_ADDRESS_WHITELIST_ENABLED: true

production:
  WHITELIST_IP_ADDRESSES:
  IP_ADDRESS_WHITELIST_ENABLED:
